default_index:
    path: /
    defaults: { _controller: "AppBundle:Default:index" }
    methods: GET

default_retiro:
    path: /api/retiro
    defaults: { _controller: "AppBundle:Default:retiro" }
    methods: POST